### ISSUE TITLE
Usage pattern for html in tables?

### ISSUE THREAD

**Issue by mmattozzi** [grid-js/gridjs-jquery#229]
Hi, thanks for the library... hoping this is just a documentation improvement, but is it possible to include HTML in tables as described in https://gridjs.io/docs/examples/html-cells ? If so, how do I import the html function using this library? Thanks!

**Comment by mmattozzi** [comment]
Oh, of note including
`<script src="https://unpkg.com/gridjs/dist/gridjs.umd.js"></script>`
and then later referencing `gridjs.html()` did work just fine for my use case, but I was wondering if there was a cleaner way that didn't involve also including that source file.

**Comment by Genaker** [comment]
the same issue
